-- -- Hibernate creates the schema. This file intentionally stays empty so the same project can switch to Postgres later.
-- CREATE TABLE products (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     sku VARCHAR(100) NOT NULL UNIQUE,
--     name VARCHAR(255) NOT NULL,
--     category VARCHAR(100) NOT NULL,
--     current_price DOUBLE NOT NULL,
--     stock_level INT NOT NULL,
--     reorder_threshold INT NOT NULL,
--     demand_velocity DOUBLE NOT NULL,
--     status VARCHAR(50) NOT NULL
-- );

-- CREATE TABLE pricing_suggestions (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     product_id BIGINT NOT NULL,
--     direction VARCHAR(50) NOT NULL,
--     percentage_change DOUBLE NOT NULL,
--     suggested_price DOUBLE NOT NULL,
--     confidence_score DOUBLE NOT NULL,
--     reasoning VARCHAR(2000),
--     status VARCHAR(50) NOT NULL,
--     trigger_reason VARCHAR(50) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_pricing_product
--         FOREIGN KEY (product_id) REFERENCES products(id)
-- );

-- CREATE TABLE reorder_suggestions (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     product_id BIGINT NOT NULL,
--     quantity INT NOT NULL,
--     confidence_score DOUBLE NOT NULL,
--     reasoning VARCHAR(2000),
--     status VARCHAR(50) NOT NULL,
--     trigger_reason VARCHAR(50) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_reorder_product
--         FOREIGN KEY (product_id) REFERENCES products(id)
-- );

CREATE TABLE products (
    id VARCHAR(50) PRIMARY KEY,
    sku VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    current_price DOUBLE NOT NULL,
    stock_level INT NOT NULL,
    reorder_threshold INT NOT NULL,
    demand_velocity DOUBLE NOT NULL,
    status VARCHAR(50) NOT NULL,
    cost_price DOUBLE,
    version BIGINT DEFAULT 0
);

CREATE TABLE pricing_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL,
    current_price DOUBLE NOT NULL,
    recommended_price DOUBLE NOT NULL,
    direction VARCHAR(50) NOT NULL,
    confidence DOUBLE NOT NULL,
    reasoning VARCHAR(2000),
    status VARCHAR(50) NOT NULL,
    trigger_reason VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pricing_product
        FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE reorder_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL,

    current_stock INT NOT NULL,
    recommended_quantity INT NOT NULL,
    suggested_lead_time_days INT NOT NULL,

    confidence DOUBLE NOT NULL,
    reasoning VARCHAR(1200) NOT NULL,

    status VARCHAR(50) NOT NULL,
    trigger_reason VARCHAR(50) NOT NULL,

    CONSTRAINT fk_reorder_product
        FOREIGN KEY (product_id) REFERENCES products(id)
);

-- CREATE TABLE reorder_suggestions (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     product_id VARCHAR(50) NOT NULL,
--     suggested_quantity INT NOT NULL,
--     confidence_score DOUBLE,
--     reasoning VARCHAR(2000),
--     status VARCHAR(50) NOT NULL,
--     trigger_reason VARCHAR(50) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_reorder_product
--         FOREIGN KEY (product_id) REFERENCES products(id)
-- );